### PR TITLE
Setup nodemailer and password reset

### PR DESCRIPTION
**Pull request by jampies**

### CODE REVIEW

**Comment by ClaudioMDS** [comment]
Looks good, although I see you removed the check to see whether a user exists before deciding which password reset email to send.

When handling a password reset email;
- One should never let the person know whether the email was sent or not client side.
- One should change the email sent depending on whether the user exists; an email including the token for a registered user email, or an email notifying the user that someone is either using their details, or the details they have on record might not match the email they are using.

[Password reset best practices](https://postmarkapp.com/guides/password-reset-email-best-practices)

If you think it's unnecessary to go so far, just let me know, otherwise I'll add it back in the next PR.

Otherwise the rest seems fine.

**Review by ClaudioMDS — APPROVED** [review]

**Comment by jampies** [comment]
@ClaudioMDS That is true, but there is always a trade-off between security and usability and in this case I think usability takes precedence. It's not a sensitive website where it can cause damage by knowing if someone else has an account. In fact, if you have a student nr email, then it's already obvious you have an account, so there's not a lot of benefit to adding this kind of security, but it does add a negative effect to usability if a user can't remember which email he made an account with or if he enters it wrong and there is no feedback to that and he ends up waiting for an email that never comes.

See: https://security.stackexchange.com/questions/98082/forgot-password-and-revealing-whether-account-exists

Let me know if you agree. We could get best of both worlds by adding a second confirm email input on the password reset page to get rid of the typos issue and then do it like it was (sending an email to say the account doesn't exist), which should resolve the usability issue.

**Comment by ClaudioMDS** [comment]
I can see what you're getting at, it makes sense when you consider that we'll likely let them know an email is taken anyway, so it feels pointless to waste computational complexity on the additional layer of checking. I think the security freak in me just tends to take over at times. Current method works fine, although I think either a second textbox or a confirmation modal might not be a bad idea to prevent typos.

**Comment by jampies** [comment]
I agree, let's add that into the backlog for a future PR.

**Pull request merged**
